name: Generate snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: anton-chl
          outputs: |
            dist/github-snake-dark.svg
          palette: "neon"
          color_snake: "#39ff14"
          color_dots: "#ff0080,#7928ca,#00ffff,#39ff14"
          background: "#0d1117"
          grid: "true"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
