name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write   # allow workflow to push to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: anton-chl
          outputs: |
            dist/github-contributions-snake.svg

      - name: Customize snake colors
        run: |
          sed -i 's|<svg|<svg><defs><linearGradient id="snakeGradient" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color:#ff69b4;stop-opacity:1"/><stop offset="100%" style="stop-color:#8a2be2;stop-opacity:1"/></linearGradient></defs>|' dist/github-contributions-snake.svg
          sed -i 's/fill="currentColor"/fill="url(#snakeGradient)"/g' dist/github-contributions-snake.svg

      - name: Commit and push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add dist/github-contributions-snake.svg
          git commit -m "chore: update snake animation" || echo "No changes to commit"
          git push

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-contributions-snake
          path: dist/github-contributions-snake.svg
